name = "Beep"
uuid = "a0a4fb26-8896-49e9-8ac1-323c2c7b1d7b"
authors = ["Bence Komarniczky"]
version = "0.1.0"

[deps]
WAV = "8149f6b0-98f6-5db9-b78f-408fbbb8ef88"

[compat]
WAV = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
